### ISSUE TITLE
Kill a process?

### ISSUE THREAD

**Issue by fosskers** [yesodweb/Shelly.hs#100]
Is there a canonical way to kill a process with Shelly? Something like:

```haskell
kill :: Int -> Sh ()
kill n = ...  -- work here
```

Thanks.

**Comment by fosskers** [comment]
Perhaps:

```haskell
kill :: Text -> Sh ()
kill n = run_ "kill" ["-15", n]
```
Then use like: `readfile pid_file >>= kill`

**Comment by gregwebs** [comment]
looks fine to me although I would convert to and from an Int

**Comment by fosskers** [comment]
Then:

```haskell
import Text.Show.Text
import qualified Data.Text as T

kill :: Int -> Sh ()
kill pid = run_ "kill" ["-15", show pid]

foo :: FilePath -> Sh ()
foo f = whenM (test_f f) $ readfile f >>= kill . read . T.unpack  -- Or is there a `read` for Text?

**Comment by gregwebs** [comment]
Yeah, that is the idea except that you would use `readMay` (see the `safe` package) and be able to produce a meaningful error when you don't get an Int. Do you want to add your final code as an example to the wiki or to an examples/ folder in the repo?

**Comment by fosskers** [comment]
I'll add an example tomorrow.

**Comment by gregwebs** [comment]
I added this to a new Shelly.Unix module on master.

**Comment by fosskers** [comment]
Hot damn, thanks.
