### ISSUE TITLE
setStdin before runHandle

### ISSUE THREAD

**Issue by ozgurakgun** [yesodweb/Shelly.hs#101]
I am not sure if my diagnosis is correct with this one.

In a program I am writing, `setStdin` followed by `run` works as expected.

However, when I use `setStdin` followed by `runHandle`, the external program doesn't seem to receive the stdin.

Is this expected behaviour? If it is not, I will try to produce a minimal failing test case.

Thanks!

**Comment by gregwebs** [comment]
There shouldn't be a difference between `run` and `runHandle` with respect to stdin: they both use the same underlying machinery that works with stdin. A minimal test case would be greatly appreciated.

**Comment by ozgurakgun** [comment]
@gregwebs, thanks for the quick response. I avoided using the stdin machinery for now but will have a look as soon as possible and get back to you.

**Comment by gregwebs** [comment]
seems like a dup of #117
