### ISSUE TITLE
[Question] Should "run" and "run_" set "pipefail" under the hood?

### ISSUE THREAD

**Issue by adinapoli** [yesodweb/Shelly.hs#103]
Hey @gregwebs ,

long time no chat!

I've been hit in production by a subtle bug (not Shelly related!) and I thought I would raise an issue to see how people feel about this. Unix pipe's semantic is such that if you have intermediate programs in your pipeline, their error code will be swallowed and "$?" will return always the last invoked command. Consider the following snippet:

``` haskell
{-# LANGUAGE OverloadedStrings #-}
module PipeTest where

import Shelly
import qualified Data.Text as T

unsafePiping :: IO ()
unsafePiping = shelly $ silently $ errExit False $ escaping False $ do
    run_ "echo" ["'bar'", "|", "ls", "/eohu", "|", "echo", "'baz'"]
    lastExitCode >>= echo . T.pack . show

safePiping :: IO ()
safePiping = shelly $ silently $ errExit False $ escaping False $ do
    run_ "set" ["-o", "pipefail", "&&", "echo", "'bar'", "|", "ls", "/eohu", "|", "echo", "'baz'"]
    lastExitCode >>= echo . T.pack . show
```

If you run this in ghci and call `unsafePiping`, `0` will be returned. But notice how the intermediate command is asking for a `ls` on a non-existing directory. I would expect, intuitively, `Shelly` to catch this and save me from shooting myself in the foot. In production we had that intermediate pipe command doing something like:

```
get_stuff_from s3 | decrypt_in_transit | upload_on_s3
```

Here `decrypt_in_transit` is something which can fail, but the result of the command from `run_` was still perfectly valid.
In the second example instead, `safePiping` returns `1` as you might expect.

My question(s) are:

- Do you think `run_` should set `pipefail` as default?
- Would make sense to have a function like:

``` haskell
runPipe_ :: FilePath -> [T.Text] -> Sh ()
runPipe_ fp args = escaping False $
  run_ "set" (["-o", "pipefail", "&&", toTextIgnore fp] <> args)
```

Thanks!
Alfredo

**Comment by gregwebs** [comment]
Yes, this is desirable behavior. The problem with your suggestion is that it is non-portable. Perhaps call the function "bash"

**Comment by adinapoli** [comment]
By non-portable you mean it won't be available on non-POSIX systems or something else? Namewise `bash` works for me, as any other name. Would you be willing to accept a PR if I was going to submit it tomorrow morning?

Have a nice evening!
A.

**Comment by gregwebs** [comment]
I don't think this is guaranteed to work anywhere because it assumes bash. Yes, looking forward to your PR :). Seems like there should be both a `bash` and `bash_` version.

One more note: for the examples I think you may as well just put everything into one giant string.

**Comment by adinapoli** [comment]
Fair point well made - `pipefail` is available on bash > 3.

I'm not entirely sure about the name though, only for one reason: it conveys the idea that internally it uses `bash` to run the command, which is, last time I checked, not true. Do I remember correctly that shelly uses `sh` by default? This might throw people off a bit. What do you think?

**Comment by gregwebs** [comment]
`escaping True` actually means "don't use the system shell, just invoke the command" and `escaping False` actually means "invoke through the system shell".

The system shell which could be bash, but it could also be anything else.
It would be better for the command to run the equivalent of `bash -c "comand"`.
You could try doing this with

    escaping True $ run "/bin/bash" ["-c", "' <> T.intercalate " " args <> '"]

I am not sure if this will avoid escaping issues.

**Comment by adinapoli** [comment]
Ah, neat, I didn't have a clue that the semantic of `escaping False` was as such! I agree, we shouldn't rely on assuming users' default shell will be `bash` (although pipefail should work on the majority of shells, I'm using `zsh` and it works just fine), but I'm more concerned about escaping issues if I'm honest. 

What if we go with the following:

- We try to provide a version of both `bash` and `bash_` which works with your proposed command,modulo the addition of `pipefail` and the necessary evil to support escaping correctly.

- If doing the above would result unfeasible or more troublesome than it's worth it, we go with a simpler version (basically the one proposed in my `safePiping` example) but documenting the caveat in the documentation of the function.

How does this sound?

**Comment by gregwebs** [comment]
I wouldn't expect it to use the user's shell but instead to use the system shell. We would need to test it out to be sure.

The plan sounds good.

There is another potential POSIX-compliant option.
See http://cfajohnson.com/shell/cus-faq-2.html#Q11
And http://stackoverflow.com/questions/13084352/how-to-implement-set-o-pipefail-in-a-posix-way-almost-done-expert-help-nee

Also, please note that if you used shelly's pipe `-|-` you would get pipefail behavior at the cost of the program being less efficient. More efficient piping operators would take more effort but could be the best solution.

**Comment by adinapoli** [comment]
Agreed - I would love to be able to use `-|-` directly and having it create a proper shell pipe under the hook.

Allright, I will try to whip up a PR sometime later in the week :wink: 

Thanks!
A.

**Comment by gregwebs** [comment]
bash functions are added now
