### ISSUE TITLE
MonadShControl isn't exposed

### ISSUE THREAD

**Issue by bgamari** [yesodweb/Shelly.hs#115]
The `MonadShControl` class is not exported, making it is essentially impossible to use `verbosely`, etc. if you have encapsulated your monad stack in a `newtype`.

**Comment by gregwebs** [comment]
Is this what you need? https://github.com/yesodweb/Shelly.hs/commit/2ab177fa778e8af9ca6f0894dc69e2dca71ad6f8

**Comment by bgamari** [comment]
That ought to do it.
