### ISSUE TITLE
runHandle and (print_stderr False)

### ISSUE THREAD

**Issue by ozgurakgun** [yesodweb/Shelly.hs#117]
Hi,

I had reported another issue (#101) a while back, but I never followed up. I am not using the `setStdin` functionality any more, so I won't revisit it now either.

However, I am learning. This time I wrote a small program to reproduce the issue. :)

Here it is: https://gist.github.com/ozgurakgun/1f1917dc781f8f230dcf

It is a simple program which will call `grep` with the command line arguments given to it. I chose grep because it was the first command I could think of where I could make it print to stderr.

In the gist, you will see a terminal session where I run the program 3 times. In the first two runs stderr is empty and the program functions as expected. In the third run grep prints out a message to stderr. I do not want this message to be written to stderr of my program, hence setting print_stderr to False.

Please let me know if I need to provide more info.

Thanks!

**Comment by gregwebs** [comment]
Thanks for the report. This is fixed on master now, will release in a bit.
