### ISSUE TITLE
Wrongly ordered output due to stdout Buffering

### ISSUE THREAD

**Issue by bitc** [yesodweb/Shelly.hs#124]
I have the following Shelly program:

```haskell
{-# LANGUAGE OverloadedStrings #-}

import Shelly

main = shelly $ do
    echo "1"
    run_ "echo" ["2"]
```

I run it and get the expected output:

```
1
2
```

But if I compile it, upload it to a server, and run it through ssh, I get the wrong output!

```
$ scp myShellyScript bitc@example.com:
$ ssh bitc@example.com ./myShellyScript
2
1
```

This appears to be due to the fact that when running a program over ssh, it runs with stdout set to block buffering mode rather than line buffering.

If we switch the first line to `echo_n "1\n"`, then it works, since Shelly's implementation of "echo_n" contains an explicit "hFlush stdout" call.

Another solution is to add the statement `hSetBuffering stdout LineBuffering` to the beginning of "main".

I am not sure if this is a bug in Shelly, or expected behavior, but it surprised me, and took me a while to figure out what was going on...

**Comment by gregwebs** [comment]
I think shelly should help you out here. I am wary of changing the global (stdout) buffering mode. I just made a commit to flush the echos an added a note about the buffer setting to the README.
