### ISSUE TITLE
hackage shelly-1.6.8.5 build failure

### ISSUE THREAD

**Issue by ddssff** [yesodweb/Shelly.hs#156]
The executables are missing hs-source-dirs and build-depends entries:
```
executable  drain
    hs-source-dirs: test/examples
    main-is: drain.hs
    build-depends: base, shelly, text

executable  run-handles
    hs-source-dirs: test/examples
    main-is: run-handles.hs
    build-depends: base, shelly

executable  Color
    hs-source-dirs: test/examples
    main-is: color.hs
    build-depends: base, shelly, process, text
```

**Comment by psibi** [comment]
@ddssff How can I reproduce this ? Travis works fine for me: https://travis-ci.org/yesodweb/Shelly.hs

I also tried building via Stack (with and without flags) in my linux box locally and everything worked fine.

**Comment by ddssff** [comment]
Well, that is odd.  It happened in the midst of a ghcjs build.  I will have to look into it.

**Comment by ddssff** [comment]
it turns out that the cabal file in github is very different from the one in the hackage tarball, which in turn is different from the tarball obtained from the https://hackage.haskell.org/package/shelly-1.6.8.5/shelly.cabal link.  Using this last one is what causes the problem.

**Comment by psibi** [comment]
That's strange. I will look into this tonight and will upload a new version.

**Comment by psibi** [comment]
Okay, so I looked into this and it seems to be a Cabal parser related bug: https://github.com/commercialhaskell/stack/issues/3549

Will see if I can workaround that issue and upload a new package.

**Comment by psibi** [comment]
I have released a new version which fixes the issue.
