### ISSUE TITLE
No way to run a command with a terminal

### ISSUE THREAD

**Issue by deepfire** [yesodweb/Shelly.hs#87]
Sometimes one may desire to provide a command with a terminal, for example so as to provide a shell to the user, or to have colorized command output.

Apparently this requires jumping through PTY-related hoops which Shelly doesn't do yet.

**Comment by gregwebs** [comment]
I don't think Shelly will ever provide this (it will require haskeline and libtinfo-dev). Instead there should be an example of how to easily use it with a terminal and possibly some adapter code for that.

**Comment by deepfire** [comment]
Hmm, System.Cmd.system from "process" [1] provides that, and depends on:
 `Dependencies: base (>=3 && <5), directory (==1.0.*), filepath (>=1.1 && <1.3), unix`

--
1. https://hackage.haskell.org/package/process-1.0.1.3/docs/System-Cmd.html

**Comment by gregwebs** [comment]
I am very confused now. I thought you meant an interactive terminal.

**Comment by deepfire** [comment]
Greg, `System.Cmd.rawSystem "bash" []` does just that -- launches a fully-PTY-ed interactive shell.

**Comment by deepfire** [comment]
Sorry for close/reopen noise, misclicked..

**Comment by gregwebs** [comment]
Those and Shelly are [using the same underlying machinery to create processes](https://github.com/yesodweb/Shelly.hs/blob/master/src/Shelly.hs#L339). What are the hoops that you are referring to?

**Comment by deepfire** [comment]
Greg, I can only judge by results, really.

I can suppose that the original stdio streams are connected to a PTY, which is somehow inherited from the parent process.  But by then I would be blabbering, for I have no idea, really.

**Comment by deepfire** [comment]
Greg, the experiment can be simplified, actually -- how does one get to execute "ls --color=auto" through Shelly, so that the colors actually get emitted and interpreted -- that is, seen as colorised output?

**Comment by gregwebs** [comment]
closing this in favor of #89

**Comment by gregwebs** [comment]
Try out version 1.6.1. Note that you will only get the behavior you want if you use `run_`.
