### ISSUE TITLE
Support colorized output

### ISSUE THREAD

**Issue by jetaggart** [yesodweb/Shelly.hs#89]
Sorry if I'm missing something (extremely new to Haskell), but I can't figure out how to have a shell command print color. For example:

```haskell
main = escaping False $ do
  run_ "rspec" ["--color"]
```

I can use `rawSystem` which does output in color, but I lose the ability to use pipes (afaik). I'd also like to keep everything using shelly. Anything I'm missing or is it straightforward to add color support?

**Comment by gregwebs** [comment]
Try out version 1.6.1. Note that you will only get the behavior you want if you use `run_`.

**Comment by jetaggart** [comment]
This is great. Thanks! :+1: 

Is there any possibility of supporting interactive commands with the `run_` command? i.e. `cabal repl`?

**Comment by gregwebs** [comment]
I am not sure what is needed to make that happen right now. What is the downside of using `liftIO $ rawSystem`? That the working directory and environment are not set?

**Comment by jetaggart** [comment]
Nothing, really; just curious. I currently have a command like:

``` haskell
listen = do 
  command <- cmd "cat" ".te-pipe" :: Sh Text
  let splitCommand = (map unpack . splitOn " ") $ strip command
  liftIO $ rawSystem (head splitCommand) (tail splitCommand)
  return ()
```

A more elegant way would be:

```haskell
listen = cmd "cat" ".te-pipe" -|- run_ "sh" []
```
