### ISSUE TITLE
command1 and command1_ change the order of the arguments

### ISSUE THREAD

**Issue by stphndemos** [yesodweb/Shelly.hs#90]
In particular, I was creating a command that required 1 argument for using tar - 
```
untar :: T.Text -> Sh ()
untar a = command1_ "tar" ["-xaf"] a []
```
When I tried to use this with `untar "archive.tar.gz"` it would fail when Shelly would try to run `tar archive.tar.gz -xaf`, which doesn't work because tar requires arguments in a specific order. There are other commands in unixland that require the arguments to be in a specific order as well. I would think that `command1` and `command1_` would respect the order the arguments were passed to them. 

It's pretty easy to find in the source where this is happening, and it seem rather explicit. I could certainly fix it and send over a pull request, but I wanted to see if there was some reason why it was this way, or if it should stay like that for some reason.

**Comment by gregwebs** [comment]
Sure, send a PR. I think these do not get used much
