### ISSUE TITLE
Incorrect documentation for writefile and appendfile

### ISSUE THREAD

**Issue by gibiansky** [yesodweb/Shelly.hs#93]
The documentation for `writefile` and `appendfile` claims that they use lazy `Text`, but according to [Hackage](http://hackage.haskell.org/package/shelly-1.6.1.2/docs/Shelly.html), they use strict text (which is a change from prior versions of `Shelly`). The documentation should be fixed.

**Comment by gregwebs** [comment]
Thanks for spotting that. You can send documentation pull requests on github without ever forking/cloning the repo and just editing the file in the browser editor.
