### ISSUE TITLE
shelly-1.5.3 - ‘mask’ is not a (visible) method of class ‘Catch.MonadCatch’

### ISSUE THREAD

**Issue by slon1024** [yesodweb/Shelly.hs#94]
```
cabal install shelly-1.5.3
Resolving dependencies...
Configuring shelly-1.5.3...
Building shelly-1.5.3...
Failed to install shelly-1.5.3
Build log ( /Users/vladimir/.cabal/logs/shelly-1.5.3.log ):
Configuring shelly-1.5.3...
Building shelly-1.5.3...
Preprocessing library shelly-1.5.3...
[1 of 5] Compiling Shelly.Base      ( src/Shelly/Base.hs, dist/build/Shelly/Base.o )

src/Shelly/Base.hs:84:3:
    ‘mask’ is not a (visible) method of class ‘Catch.MonadCatch’

src/Shelly/Base.hs:86:3:
    ‘uninterruptibleMask’ is not a (visible) method of class ‘Catch.MonadCatch’
cabal: Error: some packages failed to install:
shelly-1.5.3 failed during the building phase. The exception was:
ExitFailure 1
```
I use OS X 10.9.4

```
➜ ghc --numeric-version
7.8.3
➜ cabal --version
cabal-install version 1.22.0.1
```
I don't have any problems with `1.6.1.2`, but another package try to install `1.5.3`.
Any idea how to install it?

**Comment by gregwebs** [comment]
It is probably best to convince the other package to use the latest version of Shelly.

**Comment by slon1024** [comment]
Thanks @gregwebs, maybe this make sense, but I'm not sure. 
Correct me if I'm wrong: the version `1.5.3` is broken, and if I need it - it can be problem. Because it's true, I'll do pull request with bumping version to `shelly-1.6.*`

In my case I had problem after installed `IHaskell` and next  try to install `yesod`. `Yesod` "said": I should use  `cabal install --force-reinstalls`. This action broke `IHaskell`, because after this it was trying install `shelly-1.5.3` instead of `shelly-1.6.1.2`. After some combinations (reinstalled some packages) it looks like works both :smile:.

**Comment by gregwebs** [comment]
1.5.3 is marked as deprecated. Let me know what else I can do
