### ISSUE TITLE
Drop to background?

### ISSUE THREAD

**Issue by fosskers** [yesodweb/Shelly.hs#95]
Forgive me if this is the wrong place to ask this.

Is it possible for a process started in a Shelly shell to drop to the background and run after the haskell program has ended?

**Comment by gregwebs** [comment]
I created a google group for this, but it hasn't taken off yet:
https://groups.google.com/forum/#!forum/haskell-shell-scripting

Perhaps there are StackOverflow tags that work for this?

It should be possible to do that, although I don't know how other than to use shell syntax. In a shell it is called disowning a process. The syntax is `&!` in zsh. So something like this may work

    escaping $ False $ run "zsh" ["-c 'process' &!"]

**Comment by bitc** [comment]
Maybe these links can help:

* https://hackage.haskell.org/package/daemons
* https://hackage.haskell.org/package/hdaemonize-0.5.0.1
* https://hackage.haskell.org/package/MissingH-1.3.0.2/docs/src/System-Daemon.html#detachDaemon
* https://github.com/bitc/hdevtools/blob/ad68e4921d91e0509920151a8f825470dba43015/src/Daemonize.hs

**Comment by fosskers** [comment]
Thanks, I'll close this for now as the original issue was circumvented.
