### ISSUE TITLE
Need to handle mis-encoded/binary data

### ISSUE THREAD

**Issue by hsenag** [yesodweb/Shelly.hs#96]
Similar to #83, I need to run some scripts written in a different encoding to the prevailing one as part of a test suite, and I get

    Exception: fd:8: hGetLine: invalid argument (invalid byte sequence)

from the `run` function.

Using either `hSetBinaryMode True` or `hSetEncoding char8`, fixes the problem - either inside my own `runHandles` call or by hacking `runFoldLines` in Shelly itself. With `runHandles` I lose the benefit of the processing `Shelly` does in `runFoldLines` etc.

As per the discussion in #83, some kind of hook for changing the state of a handle before Shelly reads from it would be useful for me. I'd probably prefer something generic like a `Handle -> IO ()` callback so I can choose to use binary mode or `char8` encoding, but something to just set the encoding would probably be enough.

I'm happy to write a patch for this if I could get some indication of what would be acceptable.

**Comment by gregwebs** [comment]
Thanks for your patience. Is it possible for you to modify the `sRun` part of `State` to achieve this? Then you could add a new function that modifies `sRun` just as `escaping` does.

**Comment by hsenag** [comment]
Thanks a lot for the hint.

I've got a prototype at https://github.com/hsenag/Shelly.hs/commit/869d11baf26f03e6731c14d291015ff20f98bc9b

One concern I have is that `escaping` clobbers the current state of `sRun` so if someone used that in conjunction with my new hook then the behaviour would depend on the order they were called.

Would it be worth also implementing the suggestion in the comment on https://github.com/yesodweb/Shelly.hs/blob/master/src/Shelly/Base.hs#L116 and handling escaping separately?

**Comment by gregwebs** [comment]
good point about the clobbering. Using an escaping flag does make sense and makes it easier to contend with clobbering.
